services:

  postgres:
    image: postgres:18-alpine

    environment:
      POSTGRES_DB: flagtether
      POSTGRES_USER: flagtether_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - flagtether_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U flagtether_app -d flagtether"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  flagtether:
    build:
      context: .

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flagtether
      SPRING_DATASOURCE_USERNAME: flagtether_app
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/flagtether
      SPRING_FLYWAY_USER: flagtether_app
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "false"

    ports:
      - "8080:8080"


volumes:
  flagtether_postgres_data: