spring.application.name=releasepilot

server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/releasepilot
spring.datasource.username=releasepilot_app
spring.datasource.password=${RELEASEPILOT_DB_PASSWORD}


spring.flyway.enabled=true

spring.flyway.url=jdbc:postgresql://localhost:5432/releasepilot
spring.flyway.user=releasepilot_migrator
spring.flyway.password=${RELEASEPILOT_DB_MIGRATION_PASSWORD}

spring.flyway.locations=classpath:db/migration

spring.flyway.default-schema=public
spring.flyway.schemas=public
spring.flyway.create-schemas=true

spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs